import { ExternalAccountClient } from "google-auth-library";
import { AttestationProvider } from "./attestation";

const PACKAGE_NAME = "com.ruonid.app";

// Workload Identity Federation config (generated by gcloud)
const WIF_CONFIG = {
  universe_domain: "googleapis.com",
  type: "external_account",
  audience: "//iam.googleapis.com/projects/648480773688/locations/global/workloadIdentityPools/aws-lambda-pool/providers/aws-lambda-provider",
  subject_token_type: "urn:ietf:params:aws:token-type:aws4_request",
  token_url: "https://sts.googleapis.com/v1/token",
  credential_source: {
    environment_id: "aws1",
    region_url: "http://169.254.169.254/latest/meta-data/placement/availability-zone",
    url: "http://169.254.169.254/latest/meta-data/iam/security-credentials",
    regional_cred_verification_url: "https://sts.{region}.amazonaws.com?Action=GetCallerIdentity&Version=2011-06-15",
  },
  service_account_impersonation_url: "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/play-integrity-verifier@ruonid.iam.gserviceaccount.com:generateAccessToken",
};

/**
 * Google Play Integrity provider.
 *
 * Verifies Android device attestation by decoding integrity tokens via
 * Google's decodeIntegrityToken API. Authenticates using AWS Workload
 * Identity Federation — no service account keys needed.
 */
export class PlayIntegrityProvider implements AttestationProvider {
  private client: ExternalAccountClient | null = null;

  private getClient(): ExternalAccountClient {
    if (!this.client) {
      this.client = ExternalAccountClient.fromJSON(WIF_CONFIG) as ExternalAccountClient;
      this.client.scopes = ["https://www.googleapis.com/auth/playintegrity"];
    }
    return this.client;
  }

  async verify(token: string, nonce: string): Promise<string> {
    let parsed: { integrityToken: string; deviceUUID: string };
    try {
      parsed = JSON.parse(Buffer.from(token, "base64").toString("utf8"));
    } catch {
      throw new Error("Invalid Play Integrity token format");
    }

    const { integrityToken, deviceUUID } = parsed;
    if (!integrityToken) throw new Error("Missing integrityToken");
    if (!deviceUUID) throw new Error("Missing deviceUUID");

    // Get authenticated Google client
    const client = this.getClient();
    const { token: accessToken } = await client.getAccessToken();
    if (!accessToken) throw new Error("Failed to get Google access token");

    // Call Google's decodeIntegrityToken API
    const url = `https://playintegrity.googleapis.com/v1/${PACKAGE_NAME}:decodeIntegrityToken`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ integrity_token: integrityToken }),
    });

    if (!res.ok) {
      const err = await res.text().catch(() => "");
      console.error("Play Integrity API error:", res.status, err);
      throw new Error(`Play Integrity API error: ${res.status}`);
    }

    const decoded = await res.json();
    const payload = decoded.tokenPayloadExternal;
    if (!payload) {
      throw new Error("Missing tokenPayloadExternal in response");
    }

    // Verify nonce
    const requestNonce = payload.requestDetails?.nonce;
    if (!requestNonce) throw new Error("Missing nonce in integrity token");
    const expectedNonceB64 = Buffer.from(nonce).toString("base64");
    if (requestNonce !== expectedNonceB64 && requestNonce !== nonce) {
      throw new Error("Integrity token nonce mismatch");
    }

    // Verify package name
    if (payload.appIntegrity?.packageName !== PACKAGE_NAME) {
      throw new Error(`Package name mismatch: ${payload.appIntegrity?.packageName}`);
    }

    // Verify app recognition
    const appVerdict = payload.appIntegrity?.appRecognitionVerdict;
    if (appVerdict !== "PLAY_RECOGNIZED" && appVerdict !== "UNRECOGNIZED_VERSION") {
      throw new Error(`App integrity verdict: ${appVerdict}`);
    }

    // Verify device integrity
    const verdicts: string[] = payload.deviceIntegrity?.deviceRecognitionVerdict || [];
    if (!verdicts.includes("MEETS_DEVICE_INTEGRITY")) {
      throw new Error(`Device integrity insufficient: ${verdicts.join(", ") || "none"}`);
    }

    return `android:${deviceUUID}`;
  }
}
