// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "../src/TOPRFRegistry.sol";

/// @notice Deploys TOPRFRegistry with DKG ceremony data.
///         The constructor args are read from a JSON file (dkg-data.json)
///         generated by the DKG CLI after the ceremony.
contract DeployScript is Script {
    function run() external {
        uint256 deployerKey = vm.envUint("DEPLOYER_PRIVATE_KEY");

        string memory json = vm.readFile("dkg-data.json");

        bytes memory groupPublicKey = vm.parseJsonBytes(json, ".groupPublicKey");
        string memory sourceRepo = vm.parseJsonString(json, ".sourceRepo");
        uint8 threshold = uint8(vm.parseJsonUint(json, ".threshold"));

        uint256 nodeCount = vm.parseJsonUint(json, ".nodeCount");
        TOPRFRegistry.NodeRecord[] memory nodes = new TOPRFRegistry.NodeRecord[](nodeCount);

        for (uint256 i = 0; i < nodeCount; i++) {
            string memory prefix = string.concat(".nodes[", vm.toString(i), "]");
            nodes[i] = TOPRFRegistry.NodeRecord({
                nodeId: uint8(vm.parseJsonUint(json, string.concat(prefix, ".nodeId"))),
                dkgCommitment: vm.parseJsonString(json, string.concat(prefix, ".dkgCommitment")),
                attestationDocument: vm.parseJsonString(json, string.concat(prefix, ".attestationDocument")),
                verificationShare: vm.parseJsonBytes(json, string.concat(prefix, ".verificationShare"))
            });
        }

        vm.startBroadcast(deployerKey);
        TOPRFRegistry registry = new TOPRFRegistry(
            groupPublicKey,
            sourceRepo,
            threshold,
            nodes
        );
        vm.stopBroadcast();

        console.log("TOPRFRegistry deployed at:", address(registry));
        console.log("Threshold:", threshold);
        console.log("Nodes:", nodeCount);
    }
}
