#!/usr/bin/env bash
#
# Update the package-lock.json with current package URLs and SHA256 hashes.
# Run this on an Ubuntu machine (or in CI) when you want to update pinned versions.
#
# Usage: bash image/update-lock.sh
#
set -euo pipefail

LOCK="image/package-lock.json"
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

apt-get update -qq 2>/dev/null

# Resolve azure kernel package
KERNEL_PKG=$(apt-cache depends linux-image-azure 2>/dev/null | grep "Depends: linux-image-" | grep -v "linux-image-azure" | awk '{print $2}' | head -1)
MODULES_PKG=$(echo "$KERNEL_PKG" | sed 's/linux-image-/linux-modules-/')

echo "Kernel: $KERNEL_PKG"
echo "Modules: $MODULES_PKG"

# Download each package and compute hash
download_and_hash() {
    local pkg="$1"
    cd "$TMPDIR"
    apt-get download "$pkg" 2>/dev/null
    local deb=$(ls -1 *.deb | tail -1)
    local url=$(apt-cache show "$pkg" 2>/dev/null | grep "^Filename:" | head -1 | awk '{print $2}')
    local hash=$(sha256sum "$deb" | cut -d' ' -f1)
    local mirror="http://archive.ubuntu.com/ubuntu"
    echo "$mirror/$url $hash"
    rm -f *.deb
}

echo ""
echo "Computing hashes..."

SHIM=$(download_and_hash "shim-signed")
GRUB=$(download_and_hash "grub-efi-amd64-signed")
KERNEL=$(download_and_hash "$KERNEL_PKG")
MODULES=$(download_and_hash "$MODULES_PKG")
BUSYBOX=$(download_and_hash "busybox-static")
CACERTS=$(download_and_hash "ca-certificates")

# Write lockfile
cat > "$LOCK" <<EOF
{
  "_comment": "Pinned package versions for reproducible sealed image builds. Generated by: image/update-lock.sh",
  "_generated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "packages": {
    "shim-signed": {
      "url": "$(echo $SHIM | cut -d' ' -f1)",
      "sha256": "$(echo $SHIM | cut -d' ' -f2)"
    },
    "grub-efi-amd64-signed": {
      "url": "$(echo $GRUB | cut -d' ' -f1)",
      "sha256": "$(echo $GRUB | cut -d' ' -f2)"
    },
    "linux-image": {
      "url": "$(echo $KERNEL | cut -d' ' -f1)",
      "sha256": "$(echo $KERNEL | cut -d' ' -f2)"
    },
    "linux-modules": {
      "url": "$(echo $MODULES | cut -d' ' -f1)",
      "sha256": "$(echo $MODULES | cut -d' ' -f2)"
    },
    "busybox-static": {
      "url": "$(echo $BUSYBOX | cut -d' ' -f1)",
      "sha256": "$(echo $BUSYBOX | cut -d' ' -f2)"
    },
    "ca-certificates": {
      "url": "$(echo $CACERTS | cut -d' ' -f1)",
      "sha256": "$(echo $CACERTS | cut -d' ' -f2)"
    }
  }
}
EOF

echo ""
echo "Updated: $LOCK"
cat "$LOCK"
